name: firmable_dbt
version: 1.0.0

profile: firmable_dbt

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - target
  - dbt_packages

models:
  firmable_dbt:

    staging:
      +schema: staging
      +materialized: view

    marts:
      +schema: core
      +materialized: table
